# Generated by Django 4.1.13 on 2026-01-29 13:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название заявки')),
                ('description', models.TextField(verbose_name='Описание груза')),
                ('cargo_type', models.CharField(choices=[('general', 'Генеральный груз'), ('perishable', 'Скоропортящийся'), ('dangerous', 'Опасный груз'), ('live_animals', 'Живые животные'), ('valuables', 'Ценности'), ('other', 'Другое')], default='general', max_length=20, verbose_name='Тип груза')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Объем (м³)')),
                ('origin_city', models.CharField(max_length=100, verbose_name='Город отправления')),
                ('destination_city', models.CharField(max_length=100, verbose_name='Город назначения')),
                ('departure_date', models.DateField(verbose_name='Дата отправления')),
                ('arrival_date', models.DateField(verbose_name='Дата прибытия')),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='Бюджет')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активная'), ('in_progress', 'В процессе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Владелец')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
