# Generated by Django 4.1.13 on 2026-01-29 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_alter_bid_options_bid_currency_bid_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipments', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shipment',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заявка на перевозку', 'verbose_name_plural': 'Заявки на перевозку'},
        ),
        migrations.AddField(
            model_name='shipment',
            name='accepted_bid',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_for_shipment', to='bids.bid', verbose_name='Принятое предложение'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='cargo_type',
            field=models.CharField(blank=True, default='general', max_length=50, verbose_name='Тип груза'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активна'), ('in_progress', 'В работе'), ('completed', 'Завершена'), ('cancelled', 'Отменена')], default='active', max_length=20, verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='shipment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='arrival_city',
            field=models.CharField(max_length=100, verbose_name='Город назначения'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='departure_city',
            field=models.CharField(max_length=100, verbose_name='Город отправления'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='estimated_price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Ожидаемая стоимость'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipments', to=settings.AUTH_USER_MODEL, verbose_name='Владелец'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название заявки'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Вес (кг)'),
        ),
    ]
