# Generated by Django 4.1.13 on 2026-01-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('shipment', 'agent'), name='unique_pending_bid_per_agent'),
        ),
    ]
